### ISSUE TITLE
Weblate source strings are in Norwegian

### ISSUE THREAD

**Issue by sm4rk0** [thuryn/your-local-weather#94]
See [here](https://hosted.weblate.org/translate/your-local-weather/strings/sr/?type=todo&offset=3).

**Comment by thuryn** [comment]
I've seen it also. I've just fired the issue to weblate service.

**Comment by thuryn** [comment]
It's fixed, email from the weblate maintainer:

Thanks for reporting this issue, it was caused by bug in code updating translation files as it did cache updated units too aggressively. The issue has been just fixed, see https://github.com/WeblateOrg/weblate/issues/2144 for more information.

**Comment by linsui** [comment]
This happens again on some strings...

**Comment by thuryn** [comment]
Could you give me an example? I'm going to send it to weblate admin.

**Comment by sm4rk0** [comment]
It looks like [this commit](https://github.com/thuryn/your-local-weather/commit/853e240af25f7301bd013f906fc0774c74fac95a) changed it to Norwegian (doesn't look like a Weblate bug). I fixed it later in [this commit](https://github.com/thuryn/your-local-weather/commit/699ac48b95000d143b8112e8aadc6a7d2e4382d2). I've also fixed non-uniform language names for English source in [this commit](https://github.com/thuryn/your-local-weather/commit/760acd547a1ab29f931a71647026a1c05fcf37ba).

**Comment by sm4rk0** [comment]
Weblate still shows Norwegian as the source for "Abbrev N↓, NØ↙, …", although I fixed the English source for it.
